language: ruby

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head
  - jruby-head

jobs:
  allow_failures:
  - rvm: ruby-head

script: "bundle exec rake --trace"

notifications:
  recipients:
    - nahi@ruby-lang.org
